version: "2"
services:
  express_test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./node_modules/.bin/nodemon app.js
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 80:3000
